[tool.poetry]
name = "dakoda-core"
version = "0.2.0"
description = "A Python library for DAKODA corpus management and querying."
license = "Apache-2.0"
authors = [
    "Marius Hamacher <marius.hamacher@outlook.de>",
    "Josef Ruppenhofer <josef.ruppenhofer@fernuni-hagen.de>",
    "Torsten Zesch <torsten.zesch@fernuni-hagen.de>",
]
readme = "README.md"
homepage = "https://github.com/dakoda-project/dakoda-core"
repository = "https://github.com/dakoda-project/dakoda-core"
documentation = "https://github.com/dakoda-project/dakoda-core#readme"
keywords = ["dakoda", "corpus", "nlp", "uima", "linguistics"]
classifiers = [
    "License :: OSI Approved :: Apache Software License",
    "Intended Audience :: Science/Research",
    "Topic :: Text Processing :: Linguistic",
]
packages = [
    { include = "dakoda", from="src"}
]

[tool.poetry.urls]
"Bug Tracker" = "https://github.com/dakoda-project/dakoda-core/issues"

[tool.poetry.dependencies]
python = ">=3.9,<3.14"
polars = ">=1.30.0,<2.0.0"
dkpro-cassis = ">=0.10.1,<1.0.0"
xsdata = "22.12"
requests = "^2.32.0"

[tool.poetry.group.dev.dependencies]
black = "^25.1.0"
pytest = ">=8.4.0,<9.0.0"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.pytest.ini_options]
pythonpath = [
  "src"
]
filterwarnings = [
    "ignore::polars.exceptions.PolarsInefficientMapWarning",
    "ignore::xsdata.exceptions.ConverterWarning"
]